---
title: "Dépannage 2"
author: "Thierry Paré"
output:
  beamer_presentation:
    theme: "CambridgeUS"
    colortheme: "dolphin"
    fonttheme: "structurebold"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Section 1.3 : L'équation de valeur

En mathématiques financières, il ne faut pas seulement regarder les entrées et les sorties d’argent. Il faut aussi vérifier leurs positions dans le temps. 

C'est pour cette raison qu'il est primordial de faire une ligne du temps avec les entrées et les sorties de fonds!

## Section 1.4 : Le taux d'intérêt nominal
Le taux d’intérêt nominal n’est qu’une manière différente de décrire l'accumulation ou l'actualisation d'un montant d'argent. 

Sa définition est intimement liée à celle du taux d’intérêt effectif:
$$1 + i = \left( 1 + \frac{i^{(m)}}{m} \right) ^ m$$

## Section 1.5 : Le taux d'escompte
Le taux d’escompte est aussi une manière de décrire un taux qui permet d’accumuler ou d'actualiser un certain montant.

Sa définition est la suivante :

$$d = \frac{A(t + h) - A(t)}{A(t + h)}$$

La formule qui nous intéresse réellement est plutôt celle-ci :

$$ d = \frac{i}{1 + i} $$

## Section 1.5 : Le taux d'escompte

La fonction d’accumulation d’un taux d’escompte composé est la suivante :

$$ A(t) = A(0)\times (1 - d) ^{-t} $$
La fonction d’accumulation d’un taux d’escompte simple est la suivante : 
$$ A(t) = A(0)\times(1 - dt)^{-1}$$

## Section 1.5 : Le taux d'escompte

Il est aussi intéressant de définir le taux d'escompte nominal.
$$1 - d = \left(1 - \frac{d^{(m)}}{m}\right)^m$$

## Inégalité intéressante
Il peut être intéressant de se rappeler de cette inégalité :

$$ d < d^{(m)} < \delta < i^{(m)} < i$$

## Section 1.6 : La force d'intérêt
La définition de la force d’intérêt est la suivante : 
$$\delta(t) = \frac{A’(t)}{A(t)} = \frac{a’(t)}{a(t)}$$

La force d’intérêt peut être interprétée ainsi : C’est un taux nominal avec un m qui tend vers l’infini.

Fonction d’accumulation avec une force d’intérêt :

$$A(t + h) = A(t) \times \exp \left(\int_{t}^{t+h}\delta(u)\mathrm{du} \right)$$

## Section 1.7 : Inflation et taux d'intérêt
Une formule à comprendre et à se rappeler : 

$$ r = \frac {i - B}{1 + B} $$
où $r$ : taux réel, $B$ : taux d’inflation, $i$ = taux d’intérêt

Quand $i < B$, on parle d’une perte du pouvoir d’achat!